### ISSUE TITLE
PostgreSQL authentication type error : PSQLException

### ISSUE THREAD

**Issue by jongeuni** [Melan-Etumos/me-backend#2]
```
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
```
인증 유형을 지원하지 않는다는 에러가 발생했다. 

```yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: passowrd

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
```
